const bairros = {
  saoPaulo: [
    "Aclimação",
    "Água Branca",
    "Água Fria",
    "Água Funda",
    "Água Rasa",
    "Alto da Boa Vista",
    "Alto da Lapa",
    "Alto da Mooca",
    "Alto da Riviera",
    "Alto de Pinheiros",
    "Alto do Pari",
    "Altos de Vila Prudente",
    "Americanópolis",
    "Anhanguera",
    "Artur Alvim",
    "Associação Sobradinho",
    "Balneário Dom Carlos",
    "Balneário Mar Paulista",
    "Balneário São Francisco",
    "Balneário São José",
    "Barra Funda",
    "Barragem",
    "Barro Branco",
    "Bela Aliança",
    "Bela Vista",
    "Belenzinho",
    "Boacava",
    "Bom Retiro",
    "Borore",
    "Bortolândia",
    "Bosque da Saúde",
    "Bras",
    "Brasilândia",
    "Brooklin Novo",
    "Brooklin Paulista",
    "Burgo Paulista",
    "Butantã",
    "Cambuci",
    "Campininha",
    "Campo Belo",
    "Campo Grande",
    "Campo Limpo",
    "Campos Elíseos",
    "Cangaiba",
    "Canindé",
    "Cantinho Ceu",
    "Cantinho do Ceu",
    "Capão do Embira",
    "Capão Redondo",
    "Capela do Socorro",
    "Carandiru",
    "Casa Verde",
    "Casa Verde Alta",
    "Casa Verde Baixa",
    "Casa Verde Média",
    "Catumbi",
    "Caxingui",
    "Centro",
    "Cerqueira César",
    "Chácara Bandeirantes",
    "Chácara Belenzinho",
    "Chácara Bosque do Sol",
    "Chácara Califórnia",
    "Chácara Cocaia",
    "Chácara Cruzeiro do Sul",
    "Chácara da Enseada",
    "Chácara das Corujas",
    "Chácara do Conde",
    "Chácara do Sol",
    "Chácara Dona Olívia",
    "Chácara Figueira Grande",
    "Chácara Flora",
    "Chácara Flórida",
    "Chácara Gaivotas",
    "Chácara Inglesa",
    "Chácara Itaim",
    "Chácara Japonesa",
    "Chácara Jaraguá",
    "Chácara Mafalda",
    "Chácara Maria Trindade",
    "Chácara Meyer",
    "Chácara Monte Alegre",
    "Chácara Nani",
    "Chácara Nossa Senhora Aparecida",
    "Chácara Nossa Senhora do Bom Conselho",
    "Chácara Pouso Alegre",
    "Chácara Santa Etelvina",
    "Chácara Santa Maria",
    "Chácara Santana",
    "Chácara Santo Antônio",
    "Chácara Santo Hubertus",
    "Chácara São João",
    "Chácara São Luís",
    "Chácara São Silvestre",
    "Chácara Seis de Outubro",
    "Chácara Tatuapé",
    "Chácara Três Meninas",
    "Chácara Vista Alegre",
    "Chora Menino",
    "Chs Lago Grande",
    "Cidade Ademar",
    "Cidade Antônio Estêvão Carvalho",
    "Cidade Auxiliadora",
    "Cidade Centenário",
    "Cidade Continental",
    "Cidade D'abril",
    "Cidade de Deus",
    "Cidade Domitila",
    "Cidade dos Bandeirantes",
    "Cidade Dutra",
    "Cidade Ipava",
    "Cidade Jardim",
    "Cidade Júlia",
    "Cidade Kemel",
    "Cidade Líder",
    "Cidade Luz",
    "Cidade Mãe do Ceu",
    "Cidade Monções",
    "Cidade Nitro Operária",
    "Cidade Nitro Química",
    "Cidade Nova América",
    "Cidade Nova Heliopolis",
    "Cidade Nova São Miguel",
    "Cidade Patriarca",
    "Cidade Popular",
    "Cidade São Francisco",
    "Cidade São Mateus",
    "Cidade São Miguel",
    "Cidade Satélite Santa Bárbara",
    "Cidade Tiradentes",
    "Cidade Vargas",
    "Cipó do Meio",
    "City América",
    "Cohab Monet",
    "Colônia",
    "Condomínio Jequirituba",
    "Conjunto City Jaraguá",
    "Conjunto Habitacional Águia de Haia",
    "Conjunto Habitacional Área E Carvalho",
    "Conjunto Habitacional Barreira Grande",
    "Conjunto Habitacional Barro Branco I",
    "Conjunto Habitacional Barro Branco II",
    "Conjunto Habitacional Brigadeiro Eduardo Gomes",
    "Conjunto Habitacional Brigadeiro Faria Lima",
    "Conjunto Habitacional Castro Alves",
    "Conjunto Habitacional Fazenda do Carmo",
    "Conjunto Habitacional Inácio Monteiro",
    "Conjunto Habitacional Instituto Adventista",
    "Conjunto Habitacional Jardim São Bento",
    "Conjunto Habitacional Jova Rural",
    "Conjunto Habitacional Juscelino Kubitschek",
    "Conjunto Habitacional Marechal Mascarenhas Morais",
    "Conjunto Habitacional Padre José de Anchieta",
    "Conjunto Habitacional Padre Manoel da Nóbrega",
    "Conjunto Habitacional Padre Manoel de Paiva",
    "Conjunto Habitacional Parque Valo Velho Ii",
    "Conjunto Habitacional Pirajussara",
    "Conjunto Habitacional Recanto dos Humildes",
    "Conjunto Habitacional Santa Etelvina II",
    "Conjunto Habitacional Santa Etelvina III",
    "Conjunto Habitacional Sítio Conceição",
    "Conjunto Habitacional Teotônio Vilela",
    "Conjunto Habitacional Turística",
    "Conjunto Habitacional Vila Nova Cachoeirinha",
    "Conjunto Promorar Estrada da Parada",
    "Conjunto Promorar Raposo Tavares",
    "Conjunto Promorar Rio Claro",
    "Conjunto Promorar São Luís",
    "Conjunto Promorar Sapopemba",
    "Conjunto Promorar Vila Maria Iii",
    "Conjunto Residencial Alpes do Jaraguá",
    "Conjunto Residencial Butantã",
    "Conjunto Residencial Elísio Teixeira Leite",
    "Conjunto Residencial Ingai",
    "Conjunto Residencial Jardim Canaã",
    "Conjunto Residencial José Bonifácio",
    "Conjunto Residencial Morada do Sol",
    "Conjunto Residencial Novo Pacaembu",
    "Conjunto Residencial Paraíso",
    "Conjunto Residencial Prestes Maia",
    "Conjunto Residencial Sabará - Campo Grande",
    "Conjunto Residencial Salvador Tolezani",
    "Conjunto Residencial Santa Terezinha",
    "Conjunto Residencial Sítio Oratório",
    "Conjunto Residencial Vista Verde",
    "Consolação",
    "Copacabana",
    "Cupecê",
    "Cursino",
    "Educandário",
    "Eldorado",
    "Embura",
    "Engenheiro Goulart",
    "Engenheiro Marsilac",
    "Ermelino Matarazzo",
    "Estância Jaraguá",
    "Estância Mirim",
    "Estância Tangará",
    "Fazenda Aricanduva",
    "Fazenda da Juta",
    "Fazenda Itaim",
    "Fazenda Morumbi",
    "Ferreira",
    "Flor da Cantareira",
    "Freguesia do Ó",
    "Furnas",
    "Gleba do Pêssego",
    "Granja Julieta",
    "Granja Nossa Senhora Aparecida",
    "Guacuri",
    "Guaianazes",
    "Guaiauna",
    "Guapira",
    "Guarapiranga",
    "Higienópolis",
    "Horto",
    "Horto Florestal",
    "Ibirapuera",
    "Imirim",
    "Indianópolis",
    "Instituto de Previdência",
    "Interlagos",
    "Ipiranga",
    "Itaberaba",
    "Itaim Bibi",
    "Itaim Paulista",
    "Itaquera",
    "Itupu",
    "Jabaquara",
    "Jaçanã",
    "Jaguare",
    "Jaraguá",
    "Jardim Adelaide",
    "Jardim Adelfiore",
    "Jardim Adélia",
    "Jardim Adhemar de Barros",
    "Jardim Adutora",
    "Jardim Aeroporto",
    "Jardim Aida",
    "Jardim Aimoré",
    "Jardim Aladim",
    "Jardim Alfredo",
    "Jardim Almanara",
    "Jardim Almeida",
    "Jardim Almeida Prado",
    "Jardim Alpino",
    "Jardim Alto Alegre",
    "Jardim Alto Paulistano",
    "Jardim Alto Pedroso",
    "Jardim Alvina",
    "Jardim Alviverde",
    "Jardim Alvorada",
    "Jardim Alzira",
    "Jardim Amália",
    "Jardim Amaralina",
    "Jardim América",
    "Jardim América da Penha",
    "Jardim Ampliação",
    "Jardim Ana Lúcia",
    "Jardim Ana Maria",
    "Jardim Ana Rosa",
    "Jardim Anália Franco",
    "Jardim Andaraí",
    "Jardim Ângela",
    "Jardim Angelina",
    "Jardim Anhanguera",
    "Jardim Antártica",
    "Jardim Aparecida",
    "Jardim Apuana",
    "Jardim Apura",
    "Jardim Aracati",
    "Jardim Arantes",
    "Jardim Arco-íris",
    "Jardim Aricanduva",
    "Jardim Arize",
    "Jardim Arizona",
    "Jardim Arpoador",
    "Jardim Artur Alvim",
    "Jardim Assunção",
    "Jardim Ataliba Leonel",
    "Jardim Atlântico",
    "Jardim Augusta",
    "Jardim Augusto",
    "Jardim Áurea",
    "Jardim Aurélia",
    "Jardim Aurélio",
    "Jardim Aurora",
    "Jardim Avelino",
    "Jardim Avenida",
    "Jardim Azano I",
    "Jardim Azano II",
    "Jardim Bandeirante",
    "Jardim Bandeirantes",
    "Jardim Bartira",
    "Jardim Batalha",
    "Jardim Beatriz",
    "Jardim Bela Vista",
    "Jardim Belaura",
    "Jardim Belcito",
    "Jardim Belém",
    "Jardim Bélgica",
    "Jardim Benfica",
    "Jardim Bichinhos",
    "Jardim Boa Esperança",
    "Jardim Boa Vista",
    "Jardim Bom Clima",
    "Jardim Bom Pastor",
    "Jardim Bom Refúgio",
    "Jardim Bonfiglioli",
    "Jardim Bonito",
    "Jardim Borba Gato",
    "Jardim Botucatu",
    "Jardim Bransley",
    "Jardim Brasil",
    "Jardim Brasil Novo",
    "Jardim Brasília",
    "Jardim Britânia",
    "Jardim Bronzato",
    "Jardim Buriti",
    "Jardim Caboré",
    "Jardim Cabuçu",
    "Jardim Cachoeira",
    "Jardim Caguassu",
    "Jardim Camargo Novo",
    "Jardim Cambará",
    "Jardim Campinas",
    "Jardim Campo dos Ferreiros",
    "Jardim Campo Grande",
    "Jardim Campo Limpo",
    "Jardim Campos",
    "Jardim Capão Redondo",
    "Jardim Capela",
    "Jardim Capelinha",
    "Jardim Caravelas",
    "Jardim Carlu",
    "Jardim Carolina",
    "Jardim Carombe",
    "Jardim Casa Grande",
    "Jardim Casa Pintada",
    "Jardim Casablanca",
    "Jardim Castelo",
    "Jardim Castro Alves",
    "Jardim Catanduva",
    "Jardim Catarina",
    "Jardim Cecy",
    "Jardim Celeste",
    "Jardim Célia",
    "Jardim Centenário",
    "Jardim Cibele",
    "Jardim Cidade Pirituba",
    "Jardim Cidalia",
    "Jardim Cinco de Julho",
    "Jardim Clara Regina",
    "Jardim Clarice",
    "Jardim Cláudia",
    "Jardim Cleide",
    "Jardim Clímax",
    "Jardim Cliper",
    "Jardim Coimbra",
    "Jardim Colibri",
    "Jardim Colombo",
    "Jardim Colonial",
    "Jardim Colorado",
    "Jardim Comercial",
    "Jardim Concórdia",
    "Jardim Conquista",
    "Jardim Consórcio",
    "Jardim Copacabana",
    "Jardim Cordeiro",
    "Jardim Corisco",
    "Jardim Cotching",
    "Jardim Cotiana",
    "Jardim Cotinha",
    "Jardim Cris",
    "Jardim Cristal",
    "Jardim Cristália",
    "Jardim Cristina",
    "Jardim Cruz Corisco",
    "Jardim Cruzeiro",
    "Jardim D'abril",
    "Jardim da Cachoeira",
    "Jardim da Campina",
    "Jardim da Conquista",
    "Jardim da Glória",
    "Jardim da Laranjeira",
    "Jardim da Pedreira",
    "Jardim da Saúde",
    "Jardim Dalmo",
    "Jardim Damasceno",
    "Jardim Danfer",
    "Jardim das Acácias",
    "Jardim das Bandeiras",
    "Jardim das Camélias",
    "Jardim das Carmelitas",
    "Jardim das Esmeraldas",
    "Jardim das Flores",
    "Jardim das Fontes",
    "Jardim das Graças",
    "Jardim das Imbuias",
    "Jardim das Laranjeiras",
    "Jardim das Oliveiras",
    "Jardim das Palmas",
    "Jardim das Palmeiras",
    "Jardim das Pedras",
    "Jardim das Praias",
    "Jardim das Rosas",
    "Jardim das Vertentes",
    "Jardim Daysy",
    "Jardim de Lorenzo",
    "Jardim Denise",
    "Jardim Dinar",
    "Jardim Dinorah",
    "Jardim Dionísio",
    "Jardim do Alto",
    "Jardim do Campo",
    "Jardim do Carmo",
    "Jardim do Centro",
    "Jardim do Colégio",
    "Jardim do Divino",
    "Jardim do Lago",
    "Jardim do Tiro",
    "Jardim Dom Bosco",
    "Jardim Dom Fernando",
    "Jardim Dom José",
    "Jardim Domitila",
    "Jardim Dona Deolinda",
    "Jardim Dona-sinha",
    "Jardim Donaria",
    "Jardim dos Álamos",
    "Jardim dos Bichinhos",
    "Jardim dos Cataldis",
    "Jardim dos Estados",
    "Jardim dos Eucaliptos",
    "Jardim dos Francos",
    "Jardim dos Ipês",
    "Jardim dos Lagos",
    "Jardim dos Manacás",
    "Jardim dos Pereiras",
    "Jardim dos Prados",
    "Jardim Dracena",
    "Jardim Duprat",
    "Jardim Edda",
    "Jardim Edi",
    "Jardim Edilene",
    "Jardim Edith",
    "Jardim Educandário",
    "Jardim Egle",
    "Jardim Elba",
    "Jardim Eledy",
    "Jardim Eliana",
    "Jardim Eliane",
    "Jardim Elisa Maria",
    "Jardim Elísio",
    "Jardim Eliza",
    "Jardim Elizabeth",
    "Jardim Ellus",
    "Jardim Elza",
    "Jardim Ernestina",
    "Jardim Esmeralda",
    "Jardim Ester",
    "Jardim Ester Yolanda",
    "Jardim Estrela D'alva",
    "Jardim Etelvina",
    "Jardim Europa",
    "Jardim Eva",
    "Jardim Everest",
    "Jardim Fanganiello",
    "Jardim Faria Lima",
    "Jardim Felicidade",
    "Jardim Fernandes",
    "Jardim Figueira Grande",
    "Jardim Filhos da Terra",
    "Jardim Filhos Terra",
    "Jardim Flor de Maio",
    "Jardim Floresta",
    "Jardim Flórida Paulista",
    "Jardim Fluminense",
    "Jardim Fontalis",
    "Jardim Fonte do Morumbi",
    "Jardim Franca",
    "Jardim Francisco Mendes",
    "Jardim Fraternidade",
    "Jardim Fujihara",
    "Jardim Galli",
    "Jardim Germania",
    "Jardim Gianetti",
    "Jardim Gilda Maria",
    "Jardim Glória",
    "Jardim Gonzaga",
    "Jardim Grimaldi",
    "Jardim Guacuri",
    "Jardim Guaianazes",
    "Jardim Guairaca",
    "Jardim Guanabara",
    "Jardim Guanca",
    "Jardim Guanhembu",
    "Jardim Guapira",
    "Jardim Guarani",
    "Jardim Guarapiranga",
    "Jardim Guarau",
    "Jardim Guarujá",
    "Jardim Guedala",
    "Jardim Guiomar",
    "Jardim Gustavo",
    "Jardim Hadad",
    "Jardim Haia do Carrão",
    "Jardim Hebrom",
    "Jardim Helena",
    "Jardim Helga",
    "Jardim Helian",
    "Jardim Heliomar",
    "Jardim Heloísa",
    "Jardim Hercilia",
    "Jardim Herculano",
    "Jardim Herplin",
    "Jardim Hípico",
    "Jardim Humaitá",
    "Jardim Iae",
    "Jardim Ibirapuera",
    "Jardim Ibiratiba",
    "Jardim Ibitirama",
    "Jardim Icaraí",
    "Jardim Ida Guedes",
    "Jardim Ideal",
    "Jardim Iguatemi",
    "Jardim Imbé",
    "Jardim Imperador",
    "Jardim Imperial",
    "Jardim Império",
    "Jardim Indaiá",
    "Jardim Independência",
    "Jardim Ingá",
    "Jardim Internacional",
    "Jardim Ipanema",
    "Jardim Ipe",
    "Jardim Iporá",
    "Jardim Iporanga",
    "Jardim Iracema",
    "Jardim Irapiranga",
    "Jardim Irene",
    "Jardim Íris",
    "Jardim Itacolomi",
    "Jardim Itajaí",
    "Jardim Itália",
    "Jardim Itaóca",
    "Jardim Itapema",
    "Jardim Itapemirim",
    "Jardim Itapeva",
    "Jardim Itápolis",
    "Jardim Itapura",
    "Jardim Itatiaia",
    "Jardim Iv Centenário",
    "Jardim Iva",
    "Jardim Ivana",
    "Jardim Ivone",
    "Jardim Jabaquara",
    "Jardim Jaçanã",
    "Jardim Jamaica",
    "Jardim Japão",
    "Jardim Jaqueline",
    "Jardim Jaraguá",
    "Jardim Jaú",
    "Jardim Joamar",
    "Jardim Joana D'arc",
    "Jardim João Xxiii",
    "Jardim Jordão",
    "Jardim Juá",
    "Jardim Julieta",
    "Jardim Jurema",
    "Jardim Jussara",
    "Jardim Kagohara",
    "Jardim Keralux",
    "Jardim Kika",
    "Jardim Kioto",
    "Jardim Labitary",
    "Jardim Lajeado",
    "Jardim Lallo",
    "Jardim Laone",
    "Jardim Lapena",
    "Jardim Laranjeira",
    "Jardim Laranjeira - Zona Leste",
    "Jardim Laura",
    "Jardim Leila",
    "Jardim Leme",
    "Jardim Leni",
    "Jardim Leonardo",
    "Jardim Leônidas Moreira",
    "Jardim Leonor",
    "Jardim Leonor Mendes de Barros",
    "Jardim Letícia",
    "Jardim Líbano",
    "Jardim Líder",
    "Jardim Liderança",
    "Jardim Lídia",
    "Jardim Lilah",
    "Jardim Limoeiro",
    "Jardim Lisboa",
    "Jardim Londrina",
    "Jardim Los Angeles",
    "Jardim Lourdes",
    "Jardim Luanda",
    "Jardim Lucélia",
    "Jardim Lúcia",
    "Jardim Luciana",
    "Jardim Lucinda",
    "Jardim Luisa",
    "Jardim Luso",
    "Jardim Luzitania",
    "Jardim Mabel",
    "Jardim Macedônia",
    "Jardim Machado",
    "Jardim Maggi",
    "Jardim Maia",
    "Jardim Malia I",
    "Jardim Malia II",
    "Jardim Mangalot",
    "Jardim Marabá",
    "Jardim Maracá",
    "Jardim Maracanã",
    "Jardim Marajoara",
    "Jardim Marcel",
    "Jardim Marco Paulo",
    "Jardim Margarida",
    "Jardim Maria Amália",
    "Jardim Maria Augusta",
    "Jardim Maria Duarte",
    "Jardim Maria Emília",
    "Jardim Maria Estela",
    "Jardim Maria Lídia",
    "Jardim Maria Lúcia",
    "Jardim Maria Luíza",
    "Jardim Maria Nazaré",
    "Jardim Maria Rita",
    "Jardim Maria Sampaio",
    "Jardim Maria Virgínia",
    "Jardim Mariane",
    "Jardim Marilda",
    "Jardim Marília",
    "Jardim Mariliza",
    "Jardim Marilu",
    "Jardim Maringá",
    "Jardim Marisa",
    "Jardim Maristela",
    "Jardim Marpu",
    "Jardim Marquesa",
    "Jardim Martini",
    "Jardim Martinica",
    "Jardim Martins Silva",
    "Jardim Matarazzo",
    "Jardim Mazza",
    "Jardim Meliunas",
    "Jardim Melo",
    "Jardim Mimar",
    "Jardim Miragaia",
    "Jardim Mirante",
    "Jardim Miriam",
    "Jardim Mitsutani",
    "Jardim Modelo",
    "Jardim Mônica",
    "Jardim Monjolo",
    "Jardim Monte Alegre",
    "Jardim Monte Azul",
    "Jardim Monte Belo",
    "Jardim Monte Kemel",
    "Jardim Monte Verde",
    "Jardim Morais Prado",
    "Jardim Moreno",
    "Jardim Morro Verde",
    "Jardim Morumbi",
    "Jardim Mutinga",
    "Jardim Myrna",
    "Jardim Nadir",
    "Jardim Nair",
    "Jardim Nakamura",
    "Jardim Namba",
    "Jardim Naufal",
    "Jardim Nazareth",
    "Jardim Neide",
    "Jardim Neila",
    "Jardim Nélia",
    "Jardim Nélia IV",
    "Jardim Nelly",
    "Jardim Nice",
    "Jardim Ninho Verde II",
    "Jardim Niterói",
    "Jardim Nizia",
    "Jardim Noêmia",
    "Jardim Nordeste",
    "Jardim Norma",
    "Jardim Noronha",
    "Jardim Nossa Senhora Aparecida",
    "Jardim Nossa Senhora do Carmo",
    "Jardim Nosso Lar",
    "Jardim Nova Conquista",
    "Jardim Nova Germania",
    "Jardim Nova Guaianazes",
    "Jardim Nova Harmonia",
    "Jardim Nova Tereza",
    "Jardim Nova Vitória I",
    "Jardim Nova Vitória II",
    "Jardim Nove de Julho",
    "Jardim Novo Carrão",
    "Jardim Novo Horizonte",
    "Jardim Novo Jaú",
    "Jardim Novo Lar",
    "Jardim Novo Mundo",
    "Jardim Novo Pantanal",
    "Jardim Novo Parelheiros",
    "Jardim Novo Santo Amaro",
    "Jardim Novo Taboão",
    "Jardim Odete",
    "Jardim Olinda",
    "Jardim Olympia",
    "Jardim Ondina",
    "Jardim Orbam",
    "Jardim Oriental",
    "Jardim Orly",
    "Jardim Palmares",
    "Jardim Palmares - Zona Norte",
    "Jardim Panorama",
    "Jardim Panorama D'oeste",
    "Jardim Pantanal",
    "Jardim Papai Noel",
    "Jardim Paquetá",
    "Jardim Paraguaçu",
    "Jardim Paraíso",
    "Jardim Paraná",
    "Jardim Paris",
    "Jardim Parque Morumbi",
    "Jardim Patente",
    "Jardim Patente Novo",
    "Jardim Paulista",
    "Jardim Paulistano",
    "Jardim Paulo Afonso",
    "Jardim Paulo Vi",
    "Jardim Pedra Branca",
    "Jardim Pedras",
    "Jardim Pedro José Nunes",
    "Jardim Penha",
    "Jardim Pereira Leite",
    "Jardim Pereiras",
    "Jardim Peri",
    "Jardim Peri Novo",
    "Jardim Peri Peri",
    "Jardim Pérola I",
    "Jardim Pérola II",
    "Jardim Pérola III",
    "Jardim Petrópolis",
    "Jardim Picolo",
    "Jardim Pinheiros",
    "Jardim Piqueroby",
    "Jardim Piracuama",
    "Jardim Pirajussara",
    "Jardim Piratininga",
    "Jardim Pirituba",
    "Jardim Planalto",
    "Jardim Ponte Rasa",
    "Jardim Popular",
    "Jardim Portal I E II",
    "Jardim Porteira Grande",
    "Jardim Pouso Alegre",
    "Jardim Prainha",
    "Jardim Premiano",
    "Jardim Presidente",
    "Jardim Previdência",
    "Jardim Primavera",
    "Jardim Princesa",
    "Jardim Progresso",
    "Jardim Promissão",
    "Jardim Prudência",
    "Jardim Quarto Centenário",
    "Jardim Quisisana",
    "Jardim Ramala",
    "Jardim Raposo Tavares",
    "Jardim Real",
    "Jardim Recanto do Sol",
    "Jardim Recanto Verde",
    "Jardim Record",
    "Jardim Recreio",
    "Jardim Redenção",
    "Jardim Redil",
    "Jardim Regina",
    "Jardim Régis",
    "Jardim Reimberg",
    "Jardim Represa",
    "Jardim República",
    "Jardim Ribilene",
    "Jardim Ricardo",
    "Jardim Rincão",
    "Jardim Rio Bonito",
    "Jardim Rio Douro",
    "Jardim Rio Pequeno",
    "Jardim Riviera",
    "Jardim Rizzo",
    "Jardim Robru",
    "Jardim Rodolfo Pirani",
    "Jardim Romano",
    "Jardim Roni",
    "Jardim Rosa Maria",
    "Jardim Rosana",
    "Jardim Roschel",
    "Jardim Roseli",
    "Jardim Rosina",
    "Jardim Rosinha",
    "Jardim Rossin",
    "Jardim Rubilene",
    "Jardim Rubio",
    "Jardim Russo",
    "Jardim Ruth",
    "Jardim S Kemel",
    "Jardim Sabará",
    "Jardim Sabiá",
    "Jardim Sabiá II",
    "Jardim Sagrado Coração",
    "Jardim Samambaia",
    "Jardim Samara",
    "Jardim Sandra",
    "Jardim Sandra Maria",
    "Jardim Santa Adélia",
    "Jardim Santa Bárbara",
    "Jardim Santa Cruz",
    "Jardim Santa Edwiges",
    "Jardim Santa Efigênia",
    "Jardim Santa Emília",
    "Jardim Santa Etelvina",
    "Jardim Santa Fé",
    "Jardim Santa Filomena",
    "Jardim Santa Francisca Cabrini",
    "Jardim Santa Gertrudes",
    "Jardim Santa Helena",
    "Jardim Santa Ines",
    "Jardim Santa Josefina",
    "Jardim Santa Lucrécia",
    "Jardim Santa Margarida",
    "Jardim Santa Maria",
    "Jardim Santa Mônica",
    "Jardim Santa Rita",
    "Jardim Santa Tereza",
    "Jardim Santa Terezinha",
    "Jardim Santa Zélia",
    "Jardim Santo Alberto",
    "Jardim Santo Amaro",
    "Jardim Santo André",
    "Jardim Santo Antoninho",
    "Jardim Santo Antônio",
    "Jardim Santo Elias",
    "Jardim Santo Onofre",
    "Jardim Santos Dumont",
    "Jardim São Benedito",
    "Jardim São Bento",
    "Jardim São Bento Novo",
    "Jardim São Bernardo",
    "Jardim São Carlos",
    "Jardim São Cristóvão",
    "Jardim São Francisco",
    "Jardim São Francisco de Assis",
    "Jardim São Gabriel",
    "Jardim São Gilberto",
    "Jardim São Gonçalo",
    "Jardim São Januário",
    "Jardim São João",
    "Jardim São Joaquim",
    "Jardim São Jorge",
    "Jardim São José",
    "Jardim São Judas Tadeu",
    "Jardim São Luís",
    "Jardim São Manoel",
    "Jardim São Martinho",
    "Jardim São Mateus",
    "Jardim São Miguel",
    "Jardim São Nicolau",
    "Jardim São Paulo",
    "Jardim São Pedro",
    "Jardim São Rafael",
    "Jardim São Remo",
    "Jardim São Ricardo",
    "Jardim São Roberto",
    "Jardim São Roque",
    "Jardim São Saverio",
    "Jardim São Sebastião",
    "Jardim São Silvestre",
    "Jardim São Vicente",
    "Jardim São Vítor",
    "Jardim Sapopemba",
    "Jardim Sarah",
    "Jardim Satélite",
    "Jardim Seckler",
    "Jardim Selma",
    "Jardim Senice",
    "Jardim Sertãozinho",
    "Jardim Shangrilá",
    "Jardim Silva Teles",
    "Jardim Silveira",
    "Jardim Sílvia",
    "Jardim Sipramar",
    "Jardim Soares",
    "Jardim Solange",
    "Jardim Somara",
    "Jardim Sônia",
    "Jardim Sônia Ingá",
    "Jardim Sônia Regina",
    "Jardim Soraia",
    "Jardim Souza",
    "Jardim Sul São Paulo",
    "Jardim Suzana",
    "Jardim Sydney",
    "Jardim Taboão",
    "Jardim Taipas",
    "Jardim Tamoio",
    "Jardim Tanay",
    "Jardim Tango",
    "Jardim Tapera",
    "Jardim Taquaral",
    "Jardim Tenani",
    "Jardim Teresa",
    "Jardim Têxtil",
    "Jardim Thealia",
    "Jardim Thomaz",
    "Jardim Tietê",
    "Jardim Tiro Alto Pombo",
    "Jardim Toca",
    "Jardim Tremembé",
    "Jardim Três Corações",
    "Jardim Três Marias",
    "Jardim Triana",
    "Jardim Tropical",
    "Jardim Trussardi",
    "Jardim Tua",
    "Jardim Tupã",
    "Jardim Tupi",
    "Jardim Turquesa",
    "Jardim Uberaba",
    "Jardim Ubirajara",
    "Jardim Uirapuru",
    "Jardim Umarizal",
    "Jardim Umuarama",
    "Jardim União",
    "Jardim Uniserve",
    "Jardim Universidade Pinheiros",
    "Jardim Vale das Virtudes",
    "Jardim Valparaíso",
    "Jardim Valquíria",
    "Jardim Varginha",
    "Jardim Vaz de Lima",
    "Jardim Vazani",
    "Jardim Vera Cruz",
    "Jardim Vergueiro",
    "Jardim Veronia",
    "Jardim Viana",
    "Jardim Vieira",
    "Jardim Vila Carrão",
    "Jardim Vila Formosa",
    "Jardim Vila Mariana",
    "Jardim Vila Rica",
    "Jardim Vilas Boas",
    "Jardim Vilma",
    "Jardim Virgínia",
    "Jardim Virgínia Bianca",
    "Jardim Vista Alegre",
    "Jardim Vista Linda",
    "Jardim Vitória",
    "Jardim Vitória Régia",
    "Jardim Vivan",
    "Jardim Wanda",
    "Jardim Yara",
    "Jardim Zaira",
    "Jardim Zilda",
    "Jardins",
    "Jardins Recanto das Rosas",
    "Jordanópolis",
    "Jurubatuba",
    "Lajeado",
    "Lapa",
    "Lapa de Baixo",
    "Lar São Paulo",
    "Lauzane Paulista",
    "Liberdade",
    "Limão",
    "Limoeiro",
    "Loteamento City Jaraguá",
    "Luz",
    "Mandaqui",
    "Maranhão",
    "Marsilac",
    "Mata Fria",
    "Miami Paulista",
    "Mirandópolis",
    "Moema",
    "Moinho Velho",
    "Mooca",
    "Morada do Sol",
    "Morro do Índio",
    "Morro dos Ingleses",
    "Morro Grande",
    "Morumbi",
    "Nossa Senhora do O",
    "Nossa Senhora O",
    "Nova Piraju",
    "Núcleo do Engordador",
    "Núcleo Lageado",
    "Pacaembu",
    "Paineiras do Morumbi",
    "Palanque",
    "Parada",
    "Parada Inglesa",
    "Parada Xv de Novembro",
    "Parada Xv Novembro",
    "Paraíso",
    "Paraíso do Morumbi",
    "Paraisópolis",
    "Parelheiros",
    "Pari",
    "Parque Alto do Rio Bonito",
    "Parque Alves de Lima",
    "Parque Amazonas",
    "Parque Amélia",
    "Parque América",
    "Parque Anhanguera",
    "Parque Anhembi",
    "Parque Arariba",
    "Parque Artur Alvim",
    "Parque Atlântico",
    "Parque Bairro Morumbi",
    "Parque Belém",
    "Parque Boa Esperança",
    "Parque Bologne",
    "Parque Boturussu",
    "Parque Brasil",
    "Parque Bristol",
    "Parque Casa de Pedra",
    "Parque Central",
    "Parque Cisper",
    "Parque Cocaia",
    "Parque Colonial",
    "Parque Continental",
    "Parque Cristina",
    "Parque Cruzeiro do Sul",
    "Parque da Lapa",
    "Parque da Mooca",
    "Parque da Vila Prudente",
    "Parque das Árvores",
    "Parque das Cerejeiras",
    "Parque das Flores",
    "Parque das Paineiras",
    "Parque Deizy",
    "Parque do Carmo",
    "Parque do Castelo",
    "Parque do Lago",
    "Parque do Morumbi",
    "Parque do Otero",
    "Parque do Terceiro Lago",
    "Parque Dom João Neri",
    "Parque Doroteia",
    "Parque dos Bancários",
    "Parque dos Príncipes",
    "Parque Edu Chaves",
    "Parque Esmeralda",
    "Parque Esperança",
    "Parque Fernanda",
    "Parque Flamengo",
    "Parque Florestal",
    "Parque Fongaro",
    "Parque Grajaú",
    "Parque Guaianazes",
    "Parque Guarani",
    "Parque Ibirapuera",
    "Parque Imperial",
    "Parque Independência",
    "Parque Industrial",
    "Parque Industrial Tomás Edson",
    "Parque Ipe",
    "Parque Itaberaba",
    "Parque Jabaquara",
    "Parque Lagoa Rica",
    "Parque Lígia",
    "Parque Luís Mucciolo",
    "Parque Malagoli",
    "Parque Mandaqui",
    "Parque Mandi",
    "Parque Maria Alice",
    "Parque Maria Domitila",
    "Parque Maria Fernandes",
    "Parque Maria Helena",
    "Parque Maria Luíza",
    "Parque Monteiro Soares",
    "Parque Morumbi",
    "Parque Munhoz",
    "Parque Nações Unidas",
    "Parque Novo Grajaú",
    "Parque Novo Lar",
    "Parque Novo Mundo",
    "Parque Novo Santo Amaro",
    "Parque Paineiras",
    "Parque Palmas do Tremembé",
    "Parque Panamericano",
    "Parque Paulistano",
    "Parque Penha",
    "Parque Pereira",
    "Parque Peruche",
    "Parque Planalto",
    "Parque Primavera",
    "Parque Ramos Freitas",
    "Parque Rebouças",
    "Parque Recreio",
    "Parque Regina",
    "Parque Residencial Cocaia",
    "Parque Residencial D'abril",
    "Parque Residencial da Lapa",
    "Parque Residencial dos Lagos",
    "Parque Residencial Júlia",
    "Parque Residencial Oratório",
    "Parque Rodrigues Alves",
    "Parque Santa Amélia",
    "Parque Santa Bárbara",
    "Parque Santa Cecília",
    "Parque Santa Madalena",
    "Parque Santa Rita",
    "Parque Santana",
    "Parque Santo Amaro",
    "Parque Santo Antônio",
    "Parque Santo Eduardo",
    "Parque São Domingos",
    "Parque São Jorge",
    "Parque São José",
    "Parque São Lourenço",
    "Parque São Lucas",
    "Parque São Luís",
    "Parque São Miguel",
    "Parque São Paulo",
    "Parque São Rafael",
    "Parque Savoy City",
    "Parque Sevilha",
    "Parque Sônia",
    "Parque Taipas",
    "Parque Tamari",
    "Parque Tietê",
    "Parque Tomás Saraiva",
    "Parque Universitário Espírita",
    "Parque Veloso",
    "Parque Vila Maria",
    "Parque Vitória",
    "Pedreira",
    "Penha de Franca",
    "Penha França",
    "Perdizes",
    "Perus",
    "Pinheiros",
    "Piqueri",
    "Pirajussara",
    "Pirituba",
    "Planalto Paulista",
    "Ponte Pequena",
    "Ponte Rasa",
    "Praia Azul",
    "Praia da Lagoa",
    "Praia do Leblon",
    "Praia Paulistinha",
    "Praias Paulistanas",
    "Promorar Vila Maria",
    "Protendit",
    "Quarta Parada",
    "Quinta da Paineira",
    "Raposo Tavares",
    "Real Parque",
    "Recanto Alegre",
    "Recanto Ana Maria",
    "Recanto Campo Belo",
    "Recanto dos Sonhos",
    "Recanto Marisa",
    "Recanto Monte Alegre",
    "Recanto Paraíso",
    "Recanto Santo Antônio",
    "Recanto Verde do Sol",
    "República",
    "Residencial Morumbi",
    "Residencial Sol Nascente",
    "Residencial Vilela",
    "Retiro Morumbi",
    "Rio Bonito",
    "Rio Pequeno",
    "Riviera Paulista",
    "Rolinopolis",
    "Sacomã",
    "Santa Amélia",
    "Santa Cecília",
    "Santa Efigênia",
    "Santa Etelvina",
    "Santa Ifigenia",
    "Santa Teresinha",
    "Santana",
    "Santo Amaro",
    "São João Clímaco",
    "São Judas",
    "São Mateus",
    "São Miguel Paulista",
    "São Salvador",
    "Sapopemba",
    "Saúde",
    "Sé",
    "Sete Praias",
    "Siciliano",
    "Sítio Areião",
    "Sítio Barrocada",
    "Sítio Botuquara",
    "Sítio Caraguatá",
    "Sítio da Figueira",
    "Sítio do Mandaqui",
    "Sítio do Morro",
    "Sítio do Piqueri",
    "Sítio Itaberaba I",
    "Sítio Itaberaba II",
    "Sítio Morro Grande",
    "Sítio Pinheirinho",
    "Sítio Represa",
    "Socorro",
    "Sumaré",
    "Sumarezinho",
    "Super Quadra Morumbi",
    "Tatuapé",
    "Terceira Divisão",
    "Terceira Divisão de Interlagos",
    "Tremembé",
    "Três Cruzes",
    "Tucuruvi",
    "Umarizal",
    "União de Vila Nova",
    "Usina Piratininga",
    "Valo Velho",
    "Várzea Barra Funda",
    "Várzea da Barra Funda",
    "Várzea de Baixo",
    "Veleiros",
    "Vila Abc",
    "Vila Acre",
    "Vila Adalgisa",
    "Vila Água Funda",
    "Vila Agueda",
    "Vila Aimoré",
    "Vila Alabama",
    "Vila Alba",
    "Vila Albano",
    "Vila Albertina",
    "Vila Alexandria",
    "Vila Almeida",
    "Vila Alpina",
    "Vila Alzira",
    "Vila Amália",
    "Vila Amélia",
    "Vila América",
    "Vila Americana",
    "Vila Ana Rosa",
    "Vila Anadir",
    "Vila Anália",
    "Vila Anastácio",
    "Vila Andes",
    "Vila Andrade",
    "Vila Anglo Brasileira",
    "Vila Anhanguera",
    "Vila Antonieta",
    "Vila Antonina",
    "Vila Antônio",
    "Vila Antônio dos Santos",
    "Vila Aparecida",
    "Vila Aparecida Ivone",
    "Vila Araguaia",
    "Vila Arapuã",
    "Vila Arcádia",
    "Vila Aricanduva",
    "Vila Arriete",
    "Vila Arruda",
    "Vila Augusto",
    "Vila Áurea",
    "Vila Aurora",
    "Vila Aurora - Zona Norte",
    "Vila Ayrosa",
    "Vila Azevedo",
    "Vila Babilônia",
    "Vila Baby",
    "Vila Bancária",
    "Vila Bancaria Munhoz",
    "Vila Bandeirantes",
    "Vila Barbosa",
    "Vila Barreto",
    "Vila Baruel",
    "Vila Basileia",
    "Vila Bauab",
    "Vila Beatriz",
    "Vila Bela",
    "Vila Bela Aliança",
    "Vila Bela do Sapopemba",
    "Vila Bela Vista",
    "Vila Belo Horizonte",
    "Vila Bertioga",
    "Vila Bianca",
    "Vila Boacava",
    "Vila Bom Jardim",
    "Vila Bonilha",
    "Vila Bonilha Nova",
    "Vila Borges",
    "Vila Bozzini",
    "Vila Brasil",
    "Vila Brasilândia",
    "Vila Brasília",
    "Vila Brasilina",
    "Vila Brasílio Machado",
    "Vila Bruna",
    "Vila Buarque",
    "Vila Buenos Aires",
    "Vila Butantã",
    "Vila Cachoeira",
    "Vila Caiçara",
    "Vila Caiuba",
    "Vila Caju",
    "Vila Califórnia",
    "Vila Calu",
    "Vila Campanela",
    "Vila Campestre",
    "Vila Campo Grande",
    "Vila Canero",
    "Vila Capela",
    "Vila Caraguatá",
    "Vila Carbone",
    "Vila Cardoso Franco",
    "Vila Carioca",
    "Vila Carlos de Campos",
    "Vila Carmem",
    "Vila Carmosina",
    "Vila Carolina",
    "Vila Carrão",
    "Vila Castelo",
    "Vila Catupia",
    "Vila Cavaton",
    "Vila Caxambu",
    "Vila Celeste",
    "Vila Centenário",
    "Vila Central",
    "Vila Chabilândia",
    "Vila Chalot",
    "Vila Charlote",
    "Vila Chavantes",
    "Vila Chica Luisa",
    "Vila Chuca",
    "Vila Cisper",
    "Vila Clara",
    "Vila Clarice",
    "Vila Cláudia",
    "Vila Clementino",
    "Vila Cleonice",
    "Vila Comercial",
    "Vila Conceição",
    "Vila Condomínio do Pinhal",
    "Vila Condomínio Pinhal",
    "Vila Congonhas",
    "Vila Constança",
    "Vila Continental",
    "Vila Corberi",
    "Vila Cordeiro",
    "Vila Cosmopolita",
    "Vila Costa Melo",
    "Vila Cristália",
    "Vila Cruz das Almas",
    "Vila Cruzeiro",
    "Vila Cunha Bueno",
    "Vila Curuçá",
    "Vila da Paz",
    "Vila da Saúde",
    "Vila Dalila",
    "Vila Dalva",
    "Vila Damaceno",
    "Vila Danúbio Azul",
    "Vila Darli",
    "Vila das Belezas",
    "Vila das Mercês",
    "Vila Deodoro",
    "Vila Dinorah",
    "Vila Dionisia",
    "Vila Diva",
    "Vila Divina Pastora",
    "Vila do Bosque",
    "Vila do Castelo",
    "Vila do Encontro",
    "Vila do Sol",
    "Vila Dom Pedro I",
    "Vila Dom Pedro II",
    "Vila Domitila",
    "Vila Dona Augusta",
    "Vila Dona Meta",
    "Vila Dona Sara",
    "Vila Dorna",
    "Vila dos Andradas",
    "Vila dos Andrades",
    "Vila dos Minérios",
    "Vila dos Palmares",
    "Vila dos Remédios",
    "Vila Doutor Eiras",
    "Vila Duarte",
    "Vila Ede",
    "Vila Elias Nigri",
    "Vila Elida",
    "Vila Elvira",
    "Vila Elze",
    "Vila Ema",
    "Vila Emir",
    "Vila Erna",
    "Vila Ernesto",
    "Vila Escolar",
    "Vila Espanhola",
    "Vila Esperança",
    "Vila Ester",
    "Vila Euthalia",
    "Vila Fachini",
    "Vila Fanton",
    "Vila Fátima",
    "Vila Fazzeoni",
    "Vila Feliz",
    "Vila Fernandes",
    "Vila Fiat Lux",
    "Vila Fidalgo",
    "Vila Fidélis Ribeiro",
    "Vila Firmiano Pinto",
    "Vila Formosa",
    "Vila Franca",
    "Vila Franci",
    "Vila Francos",
    "Vila Friburgo",
    "Vila Frugoli",
    "Vila Fukuya",
    "Vila Gabriel",
    "Vila Gea",
    "Vila Genioli",
    "Vila Germinal",
    "Vila Gertrudes",
    "Vila Gil",
    "Vila Gilda",
    "Vila Giordano",
    "Vila Gomes",
    "Vila Gomes Cardim",
    "Vila Gouveia",
    "Vila Graciosa",
    "Vila Granada",
    "Vila Graziela",
    "Vila Guaca",
    "Vila Guacuri",
    "Vila Guaraciaba",
    "Vila Guarani",
    "Vila Guarani - Zona Sul",
    "Vila Guedes",
    "Vila Guilherme",
    "Vila Guilhermina",
    "Vila Guiomar",
    "Vila Gumercindo",
    "Vila Gustavo",
    "Vila Hamburguesa",
    "Vila Hebe",
    "Vila Helena",
    "Vila Heliopolis",
    "Vila Hermínia",
    "Vila Homero",
    "Vila Hortência",
    "Vila Icaraí",
    "Vila Ida",
    "Vila Iguaçu",
    "Vila Império",
    "Vila Inácio",
    "Vila Inah",
    "Vila Independência",
    "Vila Independente",
    "Vila Indiana",
    "Vila Industrial",
    "Vila Inglesa",
    "Vila Invernada",
    "Vila Iolanda",
    "Vila Iolanda II",
    "Vila Iorio",
    "Vila Ipojuca",
    "Vila Irmãos Arnoni",
    "Vila Isa",
    "Vila Isabel",
    "Vila Isolina Mazzei",
    "Vila Itaberaba",
    "Vila Itaim",
    "Vila Ivg",
    "Vila Ivone",
    "Vila Jacuí",
    "Vila Jaguara",
    "Vila Jaguari",
    "Vila Jaraguá",
    "Vila Joaniza",
    "Vila João Batista",
    "Vila Júlio César",
    "Vila Jurema",
    "Vila Jussara",
    "Vila Lageado",
    "Vila Lais",
    "Vila Lar Nacional",
    "Vila Leme",
    "Vila Leonor",
    "Vila Leopoldina",
    "Vila Libanesa",
    "Vila Lisboa",
    "Vila Liviero",
    "Vila Londrina",
    "Vila Lourdes",
    "Vila Lúcia",
    "Vila Lúcia Elvira",
    "Vila Luzimar",
    "Vila Macedópolis",
    "Vila Madalena",
    "Vila Mafra",
    "Vila Malvina",
    "Vila Mangalot",
    "Vila Mara",
    "Vila Maracanã",
    "Vila Marari",
    "Vila Marcelo",
    "Vila Margareth",
    "Vila Margarida",
    "Vila Maria",
    "Vila Maria Alta",
    "Vila Maria Baixa",
    "Vila Maria Eugênia",
    "Vila Maria Luisa",
    "Vila Maria Trindade",
    "Vila Maria Zélia",
    "Vila Mariana",
    "Vila Marieta",
    "Vila Marilena",
    "Vila Marina",
    "Vila Mariza Mazzei",
    "Vila Marte",
    "Vila Mascote",
    "Vila Matias",
    "Vila Matilde",
    "Vila Mazzei",
    "Vila Medeiros",
    "Vila Mendes",
    "Vila Mercedes",
    "Vila Mesquita",
    "Vila Miami",
    "Vila Michelina",
    "Vila Minerva",
    "Vila Mira",
    "Vila Mirante",
    "Vila Miriam",
    "Vila Missionária",
    "Vila Moinho Velho",
    "Vila Monte Alegre",
    "Vila Monte Santo",
    "Vila Monumento",
    "Vila Moraes",
    "Vila Moreira",
    "Vila Morgadouro",
    "Vila Morse",
    "Vila Morumbi",
    "Vila Nair",
    "Vila Nancy",
    "Vila Narciso",
    "Vila Nascente",
    "Vila Natal",
    "Vila Natália",
    "Vila Neila",
    "Vila Nelson",
    "Vila Nhocune",
    "Vila Nilo",
    "Vila Nilva",
    "Vila Nina",
    "Vila Nivi",
    "Vila Noca",
    "Vila Nogueira",
    "Vila Norma",
    "Vila Nossa Senhora Aparecida",
    "Vila Nossa Senhora do Retiro",
    "Vila Nova",
    "Vila Nova Alba",
    "Vila Nova Cachoeirinha",
    "Vila Nova Caledonia",
    "Vila Nova Carolina",
    "Vila Nova Conceição",
    "Vila Nova Curuçá",
    "Vila Nova das Belezas",
    "Vila Nova Galvão",
    "Vila Nova Jaguare",
    "Vila Nova Manchester",
    "Vila Nova Mazzei",
    "Vila Nova Parada",
    "Vila Nova Pauliceia",
    "Vila Nova Pirajussara",
    "Vila Nova Savoia",
    "Vila Nova Teresa",
    "Vila Nova Utinga",
    "Vila Nova York",
    "Vila Odete",
    "Vila Olga",
    "Vila Olímpia",
    "Vila Olinda",
    "Vila Oratório",
    "Vila Paiva",
    "Vila Palmeiras",
    "Vila Paranaguá",
    "Vila Parque Jabaquara",
    "Vila Patrimonial",
    "Vila Pauliceia",
    "Vila Paulista",
    "Vila Paulista I",
    "Vila Paulista II",
    "Vila Paulistana",
    "Vila Paulistania",
    "Vila Paulo Silas",
    "Vila Pedra Branca",
    "Vila Pedroso",
    "Vila Penteado",
    "Vila Pereira Barreto",
    "Vila Pereira Cerca",
    "Vila Perus",
    "Vila Piauí",
    "Vila Picinin",
    "Vila Pierina",
    "Vila Piracicaba",
    "Vila Pirajussara",
    "Vila Pirituba",
    "Vila Pita",
    "Vila Plana",
    "Vila Polopoli",
    "Vila Pompeia",
    "Vila Ponte Rasa",
    "Vila Popular",
    "Vila Portugal",
    "Vila Portuguesa",
    "Vila Prado",
    "Vila Praia",
    "Vila Prelado",
    "Vila Primavera",
    "Vila Princesa Isabel",
    "Vila Progredior",
    "Vila Progresso",
    "Vila Prudente",
    "Vila Quintana",
    "Vila Ramos",
    "Vila Raquel",
    "Vila Regente Feijó",
    "Vila Regina",
    "Vila Reis",
    "Vila Remo",
    "Vila Renato",
    "Vila Represa",
    "Vila Ribeiro de Barros",
    "Vila Rica",
    "Vila Rio Branco",
    "Vila Robertina",
    "Vila Romana",
    "Vila Romano",
    "Vila Romero",
    "Vila Roque",
    "Vila Rosa",
    "Vila Rosa Molla",
    "Vila Rosaria",
    "Vila Roschel",
    "Vila Roseira II",
    "Vila Rosina",
    "Vila Rubi",
    "Vila Ruela",
    "Vila Rui Barbosa",
    "Vila Sabrina",
    "Vila Salete",
    "Vila Sampaio",
    "Vila Santa Catarina",
    "Vila Santa Clara",
    "Vila Santa Cruz",
    "Vila Santa Delfina",
    "Vila Santa Edwiges",
    "Vila Santa Eulalia",
    "Vila Santa Ines",
    "Vila Santa Isabel",
    "Vila Santa Lúcia",
    "Vila Santa Maria",
    "Vila Santa Teresa",
    "Vila Santa Teresinha",
    "Vila Santa Terezinha",
    "Vila Santa Virgínia",
    "Vila Santana",
    "Vila Santista",
    "Vila Santo Antônio",
    "Vila Santo Estefano",
    "Vila Santo Estêvão",
    "Vila Santo Henrique",
    "Vila Santos",
    "Vila São Domingos",
    "Vila São Francisco",
    "Vila São Geraldo",
    "Vila São José",
    "Vila São Judas",
    "Vila São Luís",
    "Vila São Nicolau",
    "Vila São Paulo",
    "Vila São Pedro",
    "Vila São Silvestre",
    "Vila São Vicente",
    "Vila Sapopemba",
    "Vila Seabra",
    "Vila Sérgio",
    "Vila Serralheiro",
    "Vila Silva Teles",
    "Vila Sílvia",
    "Vila Simone",
    "Vila Sinhá",
    "Vila Siqueira",
    "Vila Sirene",
    "Vila Síria",
    "Vila Socorro",
    "Vila Sofia",
    "Vila Solange",
    "Vila Sônia",
    "Vila Souza",
    "Vila Stela",
    "Vila Suíça",
    "Vila Sulina",
    "Vila Suzana",
    "Vila Talarico",
    "Vila Taquari",
    "Vila Teresinha",
    "Vila Tiradentes",
    "Vila Tolstoi",
    "Vila Tramontano",
    "Vila Uberabinha",
    "Vila União",
    "Vila Universitária",
    "Vila Valdemar",
    "Vila Vasconcelos",
    "Vila Vera",
    "Vila Verde",
    "Vila Vermelha",
    "Vila Vessoni",
    "Vila Virgínia",
    "Vila Vitório Mazzei",
    "Vila Yara",
    "Vila Zat",
    "Vila Zefira",
    "Vila Zelina",
    "Vila Zilda",
    "Vila Zulmira"
  ],
  osasco: [
    "Adalgisa",
    "Aliança",
    "Ayrosa",
    "Bacharel Jardim",
    "Bandeiras",
    "Baronesa",
    "Bela Vista",
    "Bonança",
    "Bonfim",
    "Bussocaba",
    "Centro",
    "Cidade das Flores",
    "Cidade Deus",
    "Cipava",
    "City Bussocaba",
    "Conceição",
    "Continental",
    "Helena Maria",
    "Iapi",
    "Industrial Anhanguera",
    "Jaguaribe",
    "Jardim Cirino",
    "Jardim D'abril",
    "Jardim das Flores",
    "Jardim Dom Abril",
    "Jardim Elvira",
    "Jardim Flores",
    "Jardim Itabau",
    "Jardim Marieta",
    "Jardim Nogueira",
    "Jardim Padroeira",
    "Jardim Piratininga",
    "Jardim Platina",
    "Jardim Primeiro de Maio",
    "Jardim Roberto",
    "Jardim Trabalhadores",
    "Jardim Turíbio",
    "Km 18",
    "Metalúrgicos",
    "Munhoz Jr",
    "Mutinga",
    "Novo Osasco",
    "Padroeira",
    "Pestana",
    "Piratininga",
    "Portal D'oeste",
    "Presidente Altino",
    "Quitaúna",
    "Raposo Tavares",
    "Recanto Rosas",
    "Rochdale",
    "Santa Fé",
    "Santa Maria",
    "Santo Antônio",
    "São Pedro",
    "Três Montanhas",
    "Umuarama",
    "Veloso",
    "Vila Campesina",
    "Vila Comend Anunziato",
    "Vila Julieta",
    "Vila Menck",
    "Vila Osasco",
    "Vila Prado",
    "Vila Remédios",
    "Vila Yara",
    "Vila Yolanda"
  ],
  barueri: [
    "Aldeia Serra",
    "Alphaville Centro Apoio I",
    "Alphaville Comercial",
    "Alphaville Conde I",
    "Alphaville Condomínio I",
    "Alphaville Condomínio Ii",
    "Alphaville Empresarial ",
    "Alphaville Industrial",
    "Alphaville Residencial Dois",
    "Alphaville Residencial Plus",
    "Alphaville Residencial Um",
    "Alphaville Residencial Zero",
    "Bethaville I",
    "Bethaville Ii",
    "Centro",
    "Centro administrativo Coml Jubran",
    "Centro administrativo Empresário Tamboré",
    "Centro Comercial",
    "Centro Empresarial",
    "Chácara Peroba",
    "Chs Marco",
    "Condomínio C C Alphaville",
    "Condomínio Centro Comercial Alameda",
    "Empresarial 18 do Forte",
    "Jardim Alberto",
    "Jardim Audir",
    "Jardim Barueri",
    "Jardim Belval",
    "Jardim Califórnia",
    "Jardim do Líbano",
    "Jardim dos Camargos",
    "Jardim Esperança",
    "Jardim Flórida",
    "Jardim Graziela",
    "Jardim Iracema",
    "Jardim Itaparica",
    "Jardim Itaquiti",
    "Jardim Júlio",
    "Jardim Maria Cristina",
    "Jardim Maria Helena",
    "Jardim Maria Tereza",
    "Jardim Mutinga",
    "Jardim Paraíso",
    "Jardim Paulista",
    "Jardim Regina Alice",
    "Jardim Santa Cecília",
    "Jardim Santa Mônica",
    "Jardim São José",
    "Jardim São Pedro",
    "Jardim São Silvestre",
    "Jardim Silveira",
    "Jardim Timbauhy",
    "Jardim Tupã",
    "Jardim Tupan",
    "Jardim Tupanci",
    "Melville Empresarial I E II",
    "Morada dos Pássaros",
    "Nova Aldeinha",
    "Núcleo Residencial Célia Mota",
    "Outeiro São Fernando",
    "Parque Camargos",
    "Parque das Nações",
    "Parque dos Camargos",
    "Parque Esmeralda",
    "Parque Imperial",
    "Parque Ribeiro de Lima",
    "Parque Ribeiro Lima",
    "Parque Santa Luzia",
    "Parque Viana",
    "Praça Aldeia Serra I",
    "Recanto Phrynea",
    "Residencial das Estrelas",
    "Residencial Morada dos Lagos",
    "Residencial Morada Lagos",
    "Residencial Tamboré",
    "São Fernando Residência",
    "Tamboré",
    "Vale do Sol",
    "Vila Barros",
    "Vila Boa Vista",
    "Vila Ceres",
    "Vila Conceição",
    "Vila Creti",
    "Vila Engenho Novo",
    "Vila Industrial",
    "Vila Iracema",
    "Vila Militar",
    "Vila Morellato",
    "Vila Nilva",
    "Vila Nossa Senhora Aparecida",
    "Vila Nova",
    "Vila Nova Barueri",
    "Vila Osmany",
    "Vila Pindorama",
    "Vila Porto",
    "Vila Pouso Alegre",
    "Vila São Francisco",
    "Vila São João",
    "Vila São Jorge",
    "Vila São Luiz",
    "Vila São Miguel",
    "Vila São Silvestre",
    "Vila Sargento José de Paula",
    "Vila Silveira",
    "Vila Sol",
    "Vila Universal",
    "Vila Viana",
    "Votupoca"
  ],
};
module.exports = bairros;
